# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/accelerator_bd/accelerator_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_bd || ORIG_REF_NAME==accelerator_bd} -quiet] -quiet

# IP: bd/accelerator_bd/ip/accelerator_bd_processing_system7_0_0/accelerator_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==accelerator_bd_processing_system7_0_0 || ORIG_REF_NAME==accelerator_bd_processing_system7_0_0} -quiet] -quiet

# XDC: bd/accelerator_bd/accelerator_bd_ooc.xdc
