# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Engineering/Projekty/FPGA/Xilinx/Zynq7010_qmtech/Zynq7010_qmtech.srcs/sources_1/bd/accelerator_bd/ip/accelerator_bd_processing_system7_0_0/accelerator_bd_processing_system7_0_0.xci
# IP: The module: 'accelerator_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Engineering/Projekty/FPGA/Xilinx/Zynq7010_qmtech/Zynq7010_qmtech.srcs/sources_1/bd/accelerator_bd/ip/accelerator_bd_processing_system7_0_0/accelerator_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'accelerator_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Engineering/Projekty/FPGA/Xilinx/Zynq7010_qmtech/Zynq7010_qmtech.srcs/sources_1/bd/accelerator_bd/ip/accelerator_bd_processing_system7_0_0/accelerator_bd_processing_system7_0_0.xci
# IP: The module: 'accelerator_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Engineering/Projekty/FPGA/Xilinx/Zynq7010_qmtech/Zynq7010_qmtech.srcs/sources_1/bd/accelerator_bd/ip/accelerator_bd_processing_system7_0_0/accelerator_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'accelerator_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
